# This configuration is intended for development and testing purposes only.
# It is not designed or recommended for production use. The goal of this setup is to help you get started quickly.
# For production deployments, please review and apply the necessary security, performance, and scalability best practices.

services:
  app:
    build: .
    container_name: my-app #TODO: replace with you app name
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NEXT_PUBLIC_HOST: ${NEXT_PUBLIC_HOST}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      RESEND_API_KEY: ${RESEND_API_KEY}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
  db:
    image: postgres:15-alpine
    container_name: my-app-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
